name: deploy

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ] #for release
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      #Courtesy of https://www.maxivanov.io/github-actions-deploy-to-multiple-environments-from-single-workflow/
      - name: Set env vars (staging)
        if: github.ref_type == 'branch'
        run: echo "DEPLOY_DIR=${{secrets.HOME_DIRECTORY_STAGING}}" >> $GITHUB_ENV

      - name: Set env vars (prod)
        if: github.ref_type == 'tag'
        run: echo "DEPLOY_DIR=${{secrets.HOME_DIRECTORY_PRODUCTION}}" >> $GITHUB_ENV
      # Courtesy of https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            Port $SSH_PORT
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Run deploy script by ssh
        run: ssh deploy 'cd ${{ env.DEPLOY_DIR }} && bash ./scripts/deploy.sh ${{github.sha}} --no-interaction'

